---
- hosts: all
  become_method: sudo 
  become: true
  tasks:

  #  - name: init k8s clean up
  #    shell: |
  #      rm /root/.kube/config
  #      kubeadm reset -f

   - name: Remove Old Kubernetes
     yum:
      name: "{{ item }}"
      state: absent
     loop:
      - kubeadm
      - kubelet
      - kubectl
      - kubernetes-cni
      - docker

   - name: Remove old Docker version
     yum:
       name: docker-ce
       state: absent
     ignore_errors: true

   - name: AutoRemove old packages
     yum:
       autoremove: yes

   - name: Disable swap
     command: "{{item}}"
     with_items:
      - cp /etc/fstab /root/fstab
      - sed -i /"swap"/d /etc/fstab
      - swapoff -a
     ignore_errors: true

  #  - name: Adding EpelRelease for Docker install
  #    yum:
  #      name: epel-release
  #      state: latest

  #  - name: install Docker
  #    yum:
  #      name: docker
  #      state: present
  #      update_cache: true

   - name: Systemctl Daemon Reload
     ansible.builtin.systemd:
       daemon_reload: yes

  #  - name: start Docker
  #    service:
  #      name: docker
  #      state: started
  #      enabled: yes

  #  - name: disable SELinux
  #    command: setenforce 0

  #  - name: disable SELinux on reboot
  #    selinux:
  #      state: disabled

  #  - name: remove old docker
  #    yum:
  #      name: docker
  #      state: absent

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install wget
     yum:
        name: wget
        state: present

   - name: initialize docker repo
     shell: |
       wget https://download.docker.com/linux/centos/docker-ce.repo
       cp docker-ce.repo /etc/yum.repos.d/

   - name: install kubelet
     yum:
        name: kubelet
        state: present
        update_cache: true

   - name: install kubeadm
     yum:
        name: kubeadm
        state: present

   - name: install docker
     yum:
        name: docker-ce
        state: present
  
   - name: set docker cgroup driver to systemd
     shell: |
       cat > /etc/docker/daemon.json <<EOF
       {
         "exec-opts": ["native.cgroupdriver=systemd"],
         "log-driver": "json-file",
         "storage-driver": "overlay2"
       }
       EOF

   - name: Systemctl Daemon Reload
     ansible.builtin.systemd:
       daemon_reload: yes

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started
     ignore_errors: true
   
   - name: start docker
     service:
       name: docker
       enabled: yes
       state: started
     ignore_errors: true

- hosts: master
  become: yes
  become_method: sudo
  tasks:
   - name: install kubectl
     yum:
        name: kubectl
        state: present
        allow_downgrade: yes
