---
- hosts: ftp_client
  become: yes
  tasks: 
    - name: Install ftpclient
      yum: name=ftp

- hosts: ftp
  become: yes
  tasks:
    - name: Install vsftpd
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - vsftpd
    #- name: Creating a user
      #shell: userdel -r ftpuser
      #shell: useradd ftpuser -d /var/ftp/user -p $(openssl passwd password)
    - name: Disabling SELINUX
      shell: setenforce 0

    - name: Creating ftp directory
      file:
         path: /var/ftp/pub
         state: directory
         owner: ftpuser
         group: ftpuser
         mode: '0075'
    - name: Configuring /etc/vsftpd/vstfpd.conf
      shell: sudo echo "anon_root=/var/ftp/pub" >> /etc/vsftpd/vsftpd.conf
      shell: sudo echo "anonymous_enable=YES" >> /etc/vsftpd/vsftpd.conf
      shell: sudo echo "local_enable=YES" >> /etc/vsftpd/vsftpd.conf
    - name: Restart FTP service
      systemd:
         state: reloaded
         name: ftp
      systemd:
         state: stopped
         name: firewalld
