---
- name: Playbook for configuring nagios server including clients and client services monitoring
  hosts: nagios-server
  remote_user: ansible
  become: true
  roles:
    - /var/ansiblehome/Final-project/NAGIOS/nagios_install_server
